apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy-kps
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: alloy
      app.kubernetes.io/name: alloy
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics